# Generated by Django 4.1.1 on 2022-09-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_char_code', models.CharField(max_length=2)),
                ('country_tell_code', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('percent_discount', models.FloatField(blank=True, default=0, null=True)),
                ('absolute_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_state', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('dilivery_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dilivery_status', models.CharField(blank=True, choices=[('preparing for shipping', '배송 준비중'), ('ready to ship', '배송 준비 완료'), ('shipping in progress', '배송 진행중'), ('shipping complete', '배송 완료')], max_length=22)),
                ('coupon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard_app.coupon')),
                ('order_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard_app.orderplace')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard_app.product')),
            ],
            options={
                'verbose_name_plural': 'Order Histories',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard_app.coupontype'),
        ),
    ]
