# Generated by Django 4.1.1 on 2022-09-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard_app', '0002_alter_coupontype_absolute_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard_app.coupon'),
        ),
    ]
